# Generated by Django 4.2.7 on 2024-07-08 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=255, null=True, unique=True)),
                ('action', models.BooleanField(blank=True, default=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('mangement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Asset_category_link_on_management', to='management.managementdetails')),
            ],
        ),
        migrations.CreateModel(
            name='MoveableAssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=255, null=True, unique=True)),
                ('action', models.BooleanField(blank=True, default=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('mangement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MoveableAssetCategory_link_on_management', to='management.managementdetails')),
            ],
        ),
        migrations.CreateModel(
            name='MoveableAssetDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, null=True)),
                ('asset_name', models.CharField(max_length=255, null=True)),
                ('total_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('rent_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('avilable_qty', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('per_sale_amt', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('details', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('action', models.BooleanField(blank=True, default=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MoveableAssetCategory_link', to='assets.moveableassetcategory')),
                ('mangement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MoveableAssetDetails_link_on_management', to='management.managementdetails')),
            ],
        ),
        migrations.CreateModel(
            name='AssetDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, null=True)),
                ('is_booked', models.BooleanField(blank=True, default=True, null=True)),
                ('asset_name', models.CharField(max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
                ('documents', models.FileField(blank=True, null=True, upload_to='')),
                ('action', models.BooleanField(blank=True, default=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_category_link', to='assets.assetcategory')),
                ('mangement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AssetDetails_link_on_management', to='management.managementdetails')),
            ],
        ),
    ]
