# Generated by Django 4.2.7 on 2024-07-08 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temple_name', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=65, null=True)),
                ('opening_balance_type', models.CharField(blank=True, choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=255, null=True)),
                ('tax_age', models.PositiveIntegerField(default=0, null=True)),
                ('reg_no', models.CharField(blank=True, max_length=255, null=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='')),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
                ('action', models.BooleanField(blank=True, default=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('management', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_instructions', to='management.managementdetails')),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_no', models.CharField(blank=True, max_length=255, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=255, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.BooleanField(blank=True, default=True, null=True)),
                ('bank_opening_balance_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=65, null=True)),
                ('bank_opening_balance_type', models.CharField(blank=True, choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=255, null=True)),
                ('credit_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=65, null=True)),
                ('debit_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=65, null=True)),
                ('loan_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=65, null=True)),
                ('loan_repay_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=65, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('management', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management', to='management.managementdetails')),
            ],
        ),
    ]
