# Generated by Django 4.2.7 on 2024-07-08 04:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        ('festival', '0001_initial'),
        ('interest', '0001_initial'),
        ('management', '0001_initial'),
        ('balancesheet', '0001_initial'),
        ('rental', '0001_initial'),
        ('amount', '0001_initial'),
        ('sub_tariff', '0001_initial'),
        ('chit_fund', '0001_initial'),
        ('fund', '0001_initial'),
        ('death', '0001_initial'),
        ('marriage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaction_no', models.CharField(blank=True, max_length=255, null=True)),
                ('collection_category', models.CharField(choices=[('Fund', 'Fund'), ('Festival', 'Festival'), ('Rent', 'Rent'), ('Lease', 'Lease'), ('Subscription Tariff', 'Subscription Tariff'), ('Chit-fund', 'Chit-fund'), ('Balance', 'Balance'), ('Penalty', 'Penalty'), ('Tax', 'Tax'), ('Death Tariff', 'Death Tariff'), ('Marriage', 'Marriage'), ('Management Interest', 'Management Interest'), ('Chit Interest', 'Chit Interest'), ('Moveable Rent', 'Moveable Rent')], max_length=255, null=True)),
                ('interest_principle', models.BooleanField(default=False)),
                ('interest_field', models.BooleanField(default=False)),
                ('fund_name', models.CharField(blank=True, max_length=255, null=True)),
                ('present', models.BooleanField(blank=True, null=True)),
                ('fund_type', models.CharField(blank=True, max_length=255, null=True)),
                ('absent_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('exception_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('person_type', models.CharField(choices=[('Member', 'Member'), ('Other', 'Other')], max_length=255, null=True)),
                ('member_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('interst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('payment_mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=255, null=True)),
                ('pay_date', models.DateField(null=True)),
                ('comments', models.TextField(null=True)),
                ('death_name', models.CharField(blank=True, max_length=255, null=True)),
                ('festival_name', models.CharField(blank=True, max_length=255, null=True)),
                ('marriage_name', models.CharField(blank=True, max_length=255, null=True)),
                ('balance_name', models.CharField(blank=True, max_length=255, null=True)),
                ('moveable_rent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lease_name', models.CharField(blank=True, max_length=255, null=True)),
                ('chit_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_tariff_no', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_type', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Cheque', 'Cheque')], default='Cash', max_length=255, null=True)),
                ('ref_moverent_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('trans_no', models.CharField(blank=True, max_length=255, null=True)),
                ('upi_no', models.CharField(blank=True, max_length=255, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_pay', models.CharField(blank=True, choices=[('UPI', 'UPI'), ('Net Banking', 'Net Banking'), ('NEFT', 'NEFT')], max_length=255, null=True)),
                ('action', models.BooleanField(blank=True, default=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('moveable_asset_payment', models.CharField(choices=[('Paid', 'Paid'), ('Received', 'Received')], default='Received', max_length=255)),
                ('mobile_number', models.CharField(max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid mobile in 10 digit format', regex='^[6789]\\d{9}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('no_count_install', models.PositiveBigIntegerField(default=0)),
                ('amount_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CollactionDetails_link_on_PeoplesAmountDetails', to='amount.peoplesamountdetails')),
                ('bank_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BankDetails_link_on_CollectionDetails', to='management.bankdetails')),
                ('chitt_fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_chit_fund_Details', to='chit_fund.chitfundsdetails')),
                ('death_tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CollactionDetails_link_on_DeathDetails', to='death.deathdetails')),
                ('festivals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CollactionDetails_link_on_ADDFestivalDetails', to='festival.addfestivaldetails')),
                ('fund_lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CollactionDetails_link_on_FundLeaseDetailss', to='fund.fundleasedetailss')),
                ('fund_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CollactionDetails_link_on_FundMemberDetailss', to='fund.fundmemberdetailss')),
                ('funds', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CollactionDetails_link_on_FundGroupDetails', to='fund.fundgroupdetails')),
                ('interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CollactionDetails_link_on_PeopleInterestDetails', to='interest.peopleinterestdetails')),
                ('interest_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CollactionDetails_link_on_PeopleInterestbalancesheetDetails', to='balancesheet.peopleinterestbalancesheet')),
                ('management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CollactionDetails_link_on_management', to='management.managementdetails')),
                ('marriage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Collection_Details_connected_to_MarriageDetails', to='marriage.marriagedetails')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mem_linj_CollectionDetails', to='family.member_details')),
                ('moveablerent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CollactionDetails_link_on_moveablerentDetails', to='rental.movableassetsrents')),
                ('rentsandlease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CollactionDetails_link_on_RentalAndLeaseDetails', to='rental.rentalandleasedetails')),
                ('sub_tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CollactionDetails_link_on_ADDSubscriptionTariffDetails', to='sub_tariff.addsubscriptiontariffdetails')),
            ],
        ),
    ]
