# Generated by Django 4.2.7 on 2026-09-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiondetails',
            name='balance_split_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
