# Generated by Django 4.2.7 on 2024-07-08 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementTreasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_in_hand', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=65, null=True)),
                ('expence_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=65, null=True)),
                ('bank_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=65, null=True)),
                ('bank_withdraw_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=65, null=True)),
                ('loan_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=65, null=True)),
                ('loan_repay_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=65, null=True)),
                ('income_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=65, null=True)),
                ('reduce_expence_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=65, null=True)),
                ('treasure_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=65, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagementDetails_profile_link_in_ManagementTreasure', to='management.managementdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ManagementFunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('fund_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=65, null=True)),
                ('collected_fund_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=65, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FundGroupDetails_in_ManagementFunds', to='fund.fundgroupdetails')),
                ('management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagementDetails_in_ManagementFunds', to='management.managementdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ManagementBalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('opening_balance_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=65, null=True)),
                ('opening_balance_type', models.CharField(blank=True, choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=255, null=True)),
                ('managee', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagementDetails_profile_link_in_ManagementBalanceSheet', to='management.managementdetails')),
            ],
        ),
    ]
