# Generated by Django 4.2.7 on 2024-07-08 04:58

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permisions', '0001_initial'),
        ('family', '0001_initial'),
        ('management', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chit_fund', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('member_no', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('user_role', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('User', 'User'), ('Invester', 'Invester')], max_length=255, null=True)),
                ('user_native_type', models.CharField(blank=True, choices=[('Member', 'Member'), ('Other', 'Other')], max_length=255, null=True)),
                ('role_name', models.CharField(blank=True, max_length=255, null=True)),
                ('password_new', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid mobile in 10 digit format', regex='^[6789]\\d{9}$')])),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Disabled', 'Disabled'), ('Enabled', 'Enabled')], default='Enabled', max_length=200, null=True)),
                ('chit_fund_name', models.CharField(blank=True, max_length=255, null=True)),
                ('chit_fund_investor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_investor', models.BooleanField(blank=True, default=False)),
                ('person_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('othersname', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('chit_fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chit_fund_detaills', to='chit_fund.chitfundsdetails')),
                ('chit_fund_investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chit_fund_investor_user', to='chit_fund.chitfundinvesters')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagementDetails_user', to='management.managementdetails')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_link_user', to='family.member_details')),
                ('my_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_link_user', to='permisions.my_roles')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
