# Generated by Django 4.2.7 on 2024-07-08 04:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarriageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marriage_no', models.CharField(blank=True, max_length=255, null=True)),
                ('groom_native_type', models.CharField(choices=[('Member', 'Member'), ('Other', 'Other')], max_length=255, null=True)),
                ('groom_name', models.CharField(max_length=255, null=True)),
                ('groom_family_no', models.CharField(blank=True, max_length=255, null=True)),
                ('groom_address', models.TextField(blank=True, null=True)),
                ('groom_dob', models.DateField(blank=True, null=True)),
                ('groom_mobile_number', models.CharField(max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid mobile in 10 digit format', regex='^[6789]\\d{9}$')])),
                ('groom_marriage_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=65, null=True)),
                ('bride_native_type', models.CharField(blank=True, choices=[('Member', 'Member'), ('Other', 'Other')], max_length=255, null=True)),
                ('bride_name', models.CharField(max_length=255, null=True)),
                ('bride_family_no', models.CharField(blank=True, max_length=255, null=True)),
                ('bride_address', models.TextField(blank=True, null=True)),
                ('bride_dob', models.DateField(blank=True, null=True)),
                ('bride_mobile_number', models.CharField(max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid mobile in 10 digit format', regex='^[6789]\\d{9}$')])),
                ('bride_marriage_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=65, null=True)),
                ('marriage_date', models.DateField(null=True)),
                ('marriage_place', models.TextField(null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('invitation', models.FileField(blank=True, null=True, upload_to='')),
                ('marriage_certificate', models.FileField(blank=True, null=True, upload_to='')),
                ('marriage_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('action', models.BooleanField(blank=True, default=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('bride_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bride_family', to='family.fammily_details')),
                ('bride_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bride_member', to='family.member_details')),
                ('groom_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groom_family', to='family.fammily_details')),
                ('groom_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groom_member', to='family.member_details')),
                ('mangement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_link_to_marriage', to='management.managementdetails')),
                ('new_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_family', to='family.fammily_details')),
            ],
        ),
    ]
