# Generated by Django 4.2.7 on 2024-07-08 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSangamDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sangam_no', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('head_name', models.CharField(max_length=255, null=True)),
                ('head_mem_no', models.CharField(max_length=255, null=True)),
                ('secretry_name', models.CharField(max_length=255, null=True)),
                ('secretry_mem_no', models.CharField(max_length=255, null=True)),
                ('treasurey_name', models.CharField(max_length=255, null=True)),
                ('treasurey_mem_no', models.CharField(max_length=255, null=True)),
                ('starting_date', models.DateField(null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('sangam_active', models.BooleanField(blank=True, default=True, null=True)),
                ('opening_balance_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('action', models.BooleanField(blank=True, default=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('head_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sangam_heaad_member', to='family.member_details')),
                ('management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AddSangamDetails_link', to='management.managementdetails')),
            ],
        ),
        migrations.CreateModel(
            name='SangamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=255, null=True)),
                ('member_no', models.CharField(max_length=255, null=True)),
                ('action', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sangam_member', to='family.member_details')),
                ('sangama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sangama', to='sangam.addsangamdetails')),
            ],
        ),
        migrations.CreateModel(
            name='AddSangamName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sangam_name', models.CharField(max_length=255, null=True, unique=True)),
                ('action', models.BooleanField(blank=True, default=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AddSangamName_link', to='management.managementdetails')),
            ],
        ),
        migrations.AddField(
            model_name='addsangamdetails',
            name='sangam_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sangam_name_khjjgg', to='sangam.addsangamname'),
        ),
        migrations.AddField(
            model_name='addsangamdetails',
            name='secretry_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sangam_secretry_member', to='family.member_details'),
        ),
        migrations.AddField(
            model_name='addsangamdetails',
            name='treasurey_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sangam_treasurey_member', to='family.member_details'),
        ),
    ]
