"""
Django settings for temple_proj project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mysv7cte5ey@8(p&=99sot(i^1ia61==n6u+z2d(g+=^s4!582'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
# ALLOWED_HOSTS = []

# for production 
DEBUG = False
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'assets',
    'authorities',
    'chit_fund',
    'collection',
    'death',
    'expense',
    'family',
    'festival',
    'fund',
    'home',
    'income',
    'interest',
    'management',
    'marriage',
    'rental',
    'sangam',
    'sub_tariff',
    'tax',
    'token_app',
    'user',
    'notify',
    'permisions',
    'other_people',
    'amount',
    'my_tasks',
    'balancesheet',
    'treasure',
    'reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'temple_proj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'temple_proj.wsgi.application'

# django superlogin CSRF_TRUSTED_ORIGINS = ['https://temple.dev.api.ideauxbill.in','https://temple.api.ideauxbill.in','https://temple.test.api.ideauxbill.in']

CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000']

CORS_ORIGIN_ALLOW_ALL= True
CORS_ALLOW_CREDENTIALS=True

CORS_ALLOW_HEADERS = [
'accept',
'accept-encoding',
'authorization',
'content-type',
'dnt',
'origin',
'user-agent',
'X-CSRFToken',
'x-requested-with',
'rejin',
'Business',
]


CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'temple'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'USER': os.environ.get('DB_USER', 'appadmin'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'appadmin'),
        'CONN_MAX_AGE': 600,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL= 'user.User'

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

# time error fixing
USE_TZ = True
# USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
 
MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR /'media'
 

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# # light shell new bucket
# AWS_ACCESS_KEY_ID = 'AKIAQG7H242YLLEW2PSJ'
# AWS_SECRET_ACCESS_KEY = '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'
# AWS_DEFAULT_REGION = 'ap-south-1'
# AWS_STORAGE_BUCKET_NAME = 'thozil'
# AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_DEFAULT_REGION}.amazonaws.com'
# AWS_LOCATION = 'development/temple/media'

# STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'

# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# STATICFILES_STORAGE = 'storages.backends.s3boto3.S3StaticStorage'


LOGGING = {
    'version': 1,
    'loggers': {
        'django': {
            'handlers': ['file', 'file2'],  
            'level': 'DEBUG',
        },
        'login_logout': {
            'handlers': ['file3'], 
            'level': 'INFO',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': './logs/debug5.log',
            'formatter': 'simpleRe',
        },
        'file2': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': './logs/debug6.log',
            'formatter': 'simpleRe',
        },
        'file3': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': './logs/login_logout.log',  
            'formatter': 'simpleRe',
        },
    },
    'formatters': {
        'simpleRe': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
}
