# Generated by Django 4.2.7 on 2024-07-08 04:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fammily_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancestor', models.CharField(blank=True, max_length=255, null=True)),
                ('ancestor_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('women_ancestor', models.CharField(blank=True, max_length=255, null=True)),
                ('family_no', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('head_member_type', models.CharField(blank=True, choices=[('NEW', 'NEW'), ('EXCISTING', 'EXCISTING')], max_length=255, null=True)),
                ('head_native_type', models.CharField(blank=True, choices=[('NATIVE', 'NATIVE'), ('OTHERS', 'OTHERS')], max_length=255, null=True)),
                ('years_of_living', models.IntegerField(blank=True, default=0, null=True)),
                ('members_count', models.IntegerField(blank=True, default=0, null=True)),
                ('action', models.BooleanField(blank=True, default=True, null=True)),
                ('death_members_count', models.IntegerField(blank=True, default=0, null=True)),
                ('married_remove_count', models.IntegerField(blank=True, default=0, null=True)),
                ('festival_balance_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('sub_tariff_balance_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('penalty_balance_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagementDetails_profile', to='management.managementdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Member_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_no', models.CharField(blank=True, max_length=255, null=True)),
                ('member_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('member_mobile_number', models.CharField(max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid mobile in 10 digit format', regex='^[6789]\\d{9}$')])),
                ('member_dob', models.DateField(blank=True, null=True)),
                ('member_age', models.IntegerField(blank=True, default=0, null=True)),
                ('member_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('member_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('member_relation_ship', models.CharField(blank=True, choices=[('FATHER', 'FATHER'), ('DAUGHTER', 'DAUGHTER'), ('SON', 'SON'), ('WIFE', 'WIFE')], max_length=255, null=True)),
                ('member_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255, null=True)),
                ('member_balance_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('balance_pending_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('balance_amt_paid', models.BooleanField(blank=True, default=False, null=True)),
                ('balance_paid_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('member_joining_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('member_tax_eligible', models.BooleanField(blank=True, default=False, null=True)),
                ('head', models.BooleanField(blank=True, default=False, null=True)),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('releving_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('reason_for_leaving', models.TextField(blank=True, null=True)),
                ('action', models.BooleanField(blank=True, default=True, null=True)),
                ('separate', models.BooleanField(blank=True, default=False, null=True)),
                ('death', models.BooleanField(blank=True, default=False, null=True)),
                ('marriage_remove', models.BooleanField(blank=True, default=False, null=True)),
                ('adult', models.BooleanField(blank=True, default=False, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family', to='family.fammily_details')),
                ('management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagementDetails_profile_link_iii_member', to='management.managementdetails')),
            ],
        ),
    ]
