# Generated by Django 4.2.7 on 2024-07-08 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADDSubscriptionTariffDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('tariff_amount', models.DecimalField(decimal_places=2, max_digits=65, null=True)),
                ('subscription_no', models.CharField(blank=True, max_length=255, null=True)),
                ('exp_amount_type', models.CharField(blank=True, choices=[('Percentage', 'Percentage'), ('Amount', 'Amount')], max_length=255, null=True)),
                ('exp_amount', models.DecimalField(decimal_places=2, max_digits=65, null=True)),
                ('penalty_amount_type', models.CharField(blank=True, choices=[('Percentage', 'Percentage'), ('Amount', 'Amount')], max_length=255, null=True)),
                ('penalty_amt', models.DecimalField(decimal_places=2, max_digits=65, null=True)),
                ('action', models.BooleanField(blank=True, default=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagementDetails_link_ADDSubscriptionTariffDetails', to='management.managementdetails')),
            ],
        ),
    ]
