[uwsgi]
chdir = /var/www/temple/python/temple_proj/temple_proj
module = temple_proj.wsgi:application

home = /var/www/temple/python/temple_proj/temple_proj/venv  # path to your virtualenv

master = true
processes = 4

socket = /var/www/temple/python/temple_proj/temple_proj/uwsgi/temple.sock
chmod-socket = 660
vacuum = true

die-on-term = true
