# Generated by Django 4.2.7 on 2024-07-08 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeathDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=255, null=True)),
                ('death_date', models.DateField(null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='')),
                ('action', models.BooleanField(blank=True, default=True, null=True)),
                ('death_no', models.CharField(blank=True, max_length=255, null=True)),
                ('death_tariff_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=65, null=True)),
                ('tariff_peanalty', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=65, null=True)),
                ('pen_amt_type', models.CharField(choices=[('Amount', 'Amount'), ('Percentage', 'Percentage')], max_length=255, null=True)),
                ('penalty_apply_date', models.DateField(null=True)),
                ('calculated_tariff_peanalty_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=65, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('old_death', models.BooleanField(blank=True, default=False, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('mangement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manage_link_in_death', to='management.managementdetails')),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DeathDetails_member', to='family.member_details')),
            ],
        ),
    ]
