# Generated by Django 4.2.7 on 2024-07-08 04:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        ('festival', '0001_initial'),
        ('management', '0001_initial'),
        ('sub_tariff', '0001_initial'),
        ('death', '0001_initial'),
        ('marriage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeoplesJOININGAmountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('paid', models.BooleanField(blank=True, default=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagementDetails_profile_link_in_PeoplesJOININGAmountDetails', to='management.managementdetails')),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PeoplesJOININGAmountDetails_connected_to_member', to='family.member_details')),
            ],
        ),
        migrations.CreateModel(
            name='PeoplesAmountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daughters_amt', models.BooleanField(blank=True, default=False, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('paid', models.BooleanField(blank=True, default=False, null=True)),
                ('penalty', models.BooleanField(blank=True, default=False, null=True)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('exception_amount', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('exception', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(blank=True, choices=[('Festival', 'Festival'), ('Subscription Tariff', 'Subscription Tariff'), ('Marriage', 'Marriage'), ('Death', 'Death'), ('Old Balance', 'Old Balance')], max_length=255, null=True)),
                ('amount_balance', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('penalty_balance', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('total_paid_amt', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('total_bal_amt', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('death', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Amount_Details_connected_to_DeathDetails', to='death.deathdetails')),
                ('festival', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Amount_Details_connected_to_ADDFestivalDetails', to='festival.addfestivaldetails')),
                ('management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagementDetails_profile_link_in_Amount_Details', to='management.managementdetails')),
                ('marriage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Amount_Details_connected_to_MarriageDetails', to='marriage.marriagedetails')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Amount_Details_connected_to_member', to='family.member_details')),
                ('sub_tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Amount_Details_connected_to_ADDSubscriptionTariffDetails', to='sub_tariff.addsubscriptiontariffdetails')),
            ],
        ),
        migrations.CreateModel(
            name='CashTransactionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=65, null=True)),
                ('trans_type', models.CharField(choices=[('Bank To Cash', 'Bank To Cash'), ('Cash To Bank', 'Cash To Bank'), ('Loan Amount', 'Loan Amount'), ('Loan Repayment', 'Loan Repayment'), ('Bank To Bank', 'Bank To Bank'), ('Cash Borrowed', 'Cash Borrowed'), ('Cash Paid', 'Cash Paid')], max_length=255, null=True)),
                ('banks_name', models.CharField(blank=True, max_length=255, null=True)),
                ('banks2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.BooleanField(blank=True, default=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid mobile in 10 digit format', regex='^[6789]\\d{9}$')])),
                ('address', models.TextField(null=True)),
                ('member_type', models.CharField(blank=True, choices=[('Member', 'Member'), ('Other', 'Other')], max_length=255, null=True)),
                ('paid_amt', models.DecimalField(decimal_places=2, default=0, max_digits=65, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('cash_trans', models.CharField(blank=True, max_length=255, null=True)),
                ('cash_paid_amt', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('banks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CashTransactionDetails_connected_to_BankDetails', to='management.bankdetails')),
                ('banks2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CashTransactionDetails_connected_to_BankDetails2', to='management.bankdetails')),
                ('management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagementDetails_profile_link_in_CashTransactionDetails', to='management.managementdetails')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CashtransactionDetails_connected_to_member', to='family.member_details')),
            ],
        ),
    ]
