# Generated by Django 4.2.7 on 2026-09-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplesamountdetails',
            name='penalty_applied_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
