# Generated by Django 4.2.7 on 2024-07-08 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rental', '0001_initial'),
        ('management', '0001_initial'),
        ('fund', '0001_initial'),
        ('interest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalBalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('debit_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('balance_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('total_months', models.IntegerField(blank=True, default=0, null=True)),
                ('paid', models.BooleanField(blank=True, default=False, null=True)),
                ('lease', models.BooleanField(blank=True, default=False, null=True)),
                ('is_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('months_done', models.IntegerField(blank=True, default=0, null=True)),
                ('rent_add_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagementDetails_profile_link_in_FundBalanceSheetP2', to='management.managementdetails')),
                ('rental_new_amt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_new_amt', to='rental.rentalandleasedetails')),
            ],
        ),
        migrations.CreateModel(
            name='PeopleInterestBalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('principal_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('principal_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('principal_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('intrest_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('intrest_paid_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('intrest_balance_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('penalty_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('penalty_paid_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('penalty_balance_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('credit_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('debit_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('balance_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('interest_apply_date', models.DateField(null=True)),
                ('first_interest_apply', models.BooleanField(default=False)),
                ('first_penalty_apply', models.BooleanField(default=False)),
                ('paid', models.BooleanField(blank=True, default=False, null=True)),
                ('discount', models.BooleanField(blank=True, default=False, null=True)),
                ('discount_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('closed', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('pay_done', models.IntegerField(blank=True, default=0, null=True)),
                ('interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PeopleInterestDetails_link_in_PeopleInterestBalanceSheet', to='interest.peopleinterestdetails')),
                ('management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagementDetails_profile_link_in_PeopleInterestBalanceSheet', to='management.managementdetails')),
            ],
        ),
        migrations.CreateModel(
            name='MoveableRentBalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('advance_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('debit_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('balance_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('paid', models.BooleanField(blank=True, default=False, null=True)),
                ('is_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagementDetails_profile_link_in_MoveableRentBalanceSheet', to='management.managementdetails')),
                ('moveablerent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movable_rent_in_MoveableRentBalanceSheet', to='rental.movableassetsrents')),
            ],
        ),
        migrations.CreateModel(
            name='FundMembersBalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('debit_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('balance_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FundGroupDetails_link_in_FundBalanceSheet1', to='fund.fundgroupdetails')),
                ('fund_m', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FundMemberDetailss_link_in_FundBalanceSheet1', to='fund.fundmemberdetailss')),
                ('management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagementDetails_profile_link_in_FundBalanceSheetP1', to='management.managementdetails')),
            ],
        ),
        migrations.CreateModel(
            name='FundBalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('credit_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('debit_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('balance_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FundGroupDetails_link_in_FundBalanceSheet', to='fund.fundgroupdetails')),
                ('fund_lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FundLeaseDetailss_link_in_FundBalanceSheet', to='fund.fundleasedetailss')),
                ('fund_m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FundMemberDetailss_link_in_FundBalanceSheet', to='fund.fundmemberdetailss')),
                ('management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagementDetails_profile_link_in_FundBalanceSheetP', to='management.managementdetails')),
            ],
        ),
    ]
