# Generated by Django 4.2.7 on 2026-08-07 06:20

from django.db import migrations, models


def _backfill_due_date(apps, schema_editor):
    """Copy each row's ``interest.installment_date`` onto the new
    ``PeopleInterestBalanceSheet.due_date`` mirror column.  Rows with
    no upstream ``installment_date`` are left NULL (nothing to mirror)."""
    Bal = apps.get_model("balancesheet", "PeopleInterestBalanceSheet")
    updated = 0
    for bs in Bal.objects.select_related("interest").iterator():
        _idate = getattr(bs.interest, "installment_date", None) if bs.interest_id else None
        if _idate is not None and bs.due_date != _idate:
            bs.due_date = _idate
            bs.save(update_fields=["due_date"])
            updated += 1


class Migration(migrations.Migration):

    dependencies = [
        ("balancesheet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="peopleinterestbalancesheet",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(_backfill_due_date, migrations.RunPython.noop),
    ]
