# Generated by Django 4.2.7 on 2024-07-08 04:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        ('management', '0001_initial'),
        ('chit_fund', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleInterestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intrest_no', models.CharField(blank=True, max_length=255, null=True)),
                ('interest_category', models.CharField(choices=[('Interest', 'Interest'), ('Interest with capital', 'Interest with capital'), ('Installment Interest', 'Installment Interest')], max_length=255, null=True)),
                ('interest_type', models.CharField(choices=[('Management Interest', 'Management Interest'), ('Chit fund Interest', 'Chit fund Interest')], max_length=255, null=True)),
                ('chit_name', models.CharField(max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('people_type', models.CharField(choices=[('Member', 'Member'), ('Other', 'Other')], max_length=255, null=True)),
                ('people_name', models.CharField(max_length=255, null=True)),
                ('people_address', models.TextField(null=True)),
                ('people_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('people_mobile', models.CharField(max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid mobile in 10 digit format', regex='^[6789]\\d{9}$')])),
                ('principal_amt', models.DecimalField(decimal_places=2, default=0, max_digits=65, null=True)),
                ('fix_interest_rate_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('interest_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('interest_period', models.PositiveIntegerField(default=0, null=True)),
                ('interest_period_type', models.CharField(choices=[('Week', 'Week'), ('Month', 'Month'), ('Days', 'Days')], max_length=255, null=True)),
                ('interest_type_new', models.CharField(blank=True, choices=[('percentage', 'percentage'), ('amount', 'amount')], max_length=255, null=True)),
                ('interest_new_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('apply_first_interest', models.BooleanField(blank=True, default=False, null=True)),
                ('first_interest_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('final_amt_given', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('penalty_percentage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('penalty_type', models.CharField(blank=True, choices=[('percentage', 'percentage'), ('amount', 'amount')], max_length=255, null=True)),
                ('penalty_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('nominee_apply', models.BooleanField(null=True)),
                ('nominee_person_type', models.CharField(blank=True, choices=[('Member', 'Member'), ('Other', 'Other')], max_length=255, null=True)),
                ('nominee_member_name', models.CharField(max_length=255, null=True)),
                ('nominee_mobile_no', models.CharField(max_length=255, null=True)),
                ('nominee_address', models.TextField(null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=255, null=True)),
                ('installment_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('action', models.BooleanField(blank=True, default=True, null=True)),
                ('total_counts', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_counts', models.IntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('interest_date', models.DateField(blank=True, null=True)),
                ('chitt_fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chitt_fund_link_in_PeopleInterestDetails', to='chit_fund.chitfundsdetails')),
                ('management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PeopleInterestDetails_link_on_management', to='management.managementdetails')),
                ('nominee_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Member_Details_nominee_member_link_PeopleInterestDetails', to='family.member_details')),
                ('people_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mem_liiknj_PeopleInterestDetails', to='family.member_details')),
            ],
        ),
    ]
