# Generated by Django 4.2.7 on 2026-07-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="peopleinterestdetails",
            name="penalty_enabled",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
