# Generated by Django 4.2.7 on 2024-07-08 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADDExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, null=True)),
                ('action', models.BooleanField(blank=True, default=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagementDetails_EXPENSE_category_LINK', to='management.managementdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ADDExpenseNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=255, null=True)),
                ('action', models.BooleanField(blank=True, default=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagementDetails_ADDExpenseNames_LINK', to='management.managementdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ADDExpenseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, null=True)),
                ('expense_from', models.CharField(blank=True, choices=[('Festival', 'Festival'), ('Others', 'Others')], max_length=255, null=True)),
                ('others_name', models.CharField(blank=True, max_length=255, null=True)),
                ('festival_name', models.CharField(blank=True, max_length=255, null=True)),
                ('expense_name', models.CharField(max_length=255, null=True)),
                ('expense_amt', models.DecimalField(decimal_places=2, default=0, max_digits=65, null=True)),
                ('payment_mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=255, null=True)),
                ('transaction_type', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Cheque', 'Cheque')], max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_no', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=255, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('bank_pay', models.CharField(blank=True, choices=[('UPI', 'UPI'), ('Net Banking', 'Net Banking'), ('NEFT', 'NEFT')], max_length=255, null=True)),
                ('action', models.BooleanField(blank=True, default=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Bank_link_with_expp', to='management.bankdetails')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ADDExpenseCategory_EXPENSE_LINK', to='expense.addexpensecategory')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ADDExpenseNames_EXPENSE_LINK', to='expense.addexpensenames')),
                ('festival', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ADDFestivalDetails_EXPENSE_LINK', to='festival.addfestivaldetails')),
                ('management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagementDetails_EXPENSE_LINK', to='management.managementdetails')),
            ],
        ),
    ]
