# Generated by Django 4.2.7 on 2026-07-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="addexpensedetails",
            name="expense_subcategory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Chit Fund Expense", "Chit Fund Expense"),
                    ("Temple Expense", "Temple Expense"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
