# Generated by Django 4.2.7 on 2026-08-10 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chit_fund", "0001_initial"),
        ("expense", "0002_addexpensedetails_expense_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="addexpensedetails",
            name="chit_fund_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="addexpensedetails",
            name="chitt_fund",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="chit_fund.chitfundsdetails",
            ),
        ),
    ]
