# Generated by Django 4.2.7 on 2024-07-08 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        ('management', '0001_initial'),
        ('festival', '0001_initial'),
        ('sangam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADDIncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, null=True)),
                ('action', models.BooleanField(blank=True, default=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagementDetails_income_category_LINK', to='management.managementdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ADDIncomeNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_name', models.CharField(max_length=255, null=True)),
                ('action', models.BooleanField(blank=True, default=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagementDetails_ADDincomeNames_LINK', to='management.managementdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ADDIncomeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, null=True)),
                ('festival_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sangam_name', models.CharField(blank=True, max_length=255, null=True)),
                ('income_type', models.CharField(choices=[('Donation', 'Donation'), ('Offering', 'Offering'), ('Others', 'Others'), ('Sangam', 'Sangam')], max_length=255, null=True)),
                ('offering_type', models.CharField(blank=True, choices=[('Festival', 'Festival'), ('Offering Box', 'Offering Box'), ('Others', 'Others')], max_length=255, null=True)),
                ('giver_native', models.CharField(blank=True, choices=[('Native', 'Native'), ('Others', 'Others')], max_length=255, null=True)),
                ('member_name', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('income_name', models.CharField(max_length=255, null=True)),
                ('income_amt', models.DecimalField(decimal_places=2, default=0, max_digits=65, null=True)),
                ('payment_mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=255, null=True)),
                ('transaction_type', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Cheque', 'Cheque')], max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_no', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=255, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('action', models.BooleanField(blank=True, default=True, null=True)),
                ('bank_pay', models.CharField(blank=True, choices=[('UPI', 'UPI'), ('Net Banking', 'Net Banking'), ('NEFT', 'NEFT')], max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Bank_link_with_INCOME', to='management.bankdetails')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ADDincomeCategory_income_LINK', to='income.addincomecategory')),
                ('festival', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='festival_link_in_INCOME', to='festival.addfestivaldetails')),
                ('income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ADDincomename_income_LINK', to='income.addincomenames')),
                ('management_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ManagementDetails_profile_INCOME', to='management.managementdetails')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_link_member', to='family.member_details')),
                ('sangam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sangam_link_with_INCOME', to='sangam.addsangamdetails')),
            ],
        ),
    ]
