# Generated by Django 4.2.7 on 2026-07-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="addincomedetails",
            name="income_subcategory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Chit Fund Income", "Chit Fund Income"),
                    ("Temple Income", "Temple Income"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
